import { chromium } from '@playwright/test';
import {mkdir} from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1080}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:3000');
await page.getByRole('heading',{name:'Explora el inventario'}).waitFor();
await page.locator('.vehicle-card').first().waitFor();
await mkdir('test-results',{recursive:true});
await page.screenshot({path:'test-results/inventario.png',fullPage:true});
await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();
await page.getByLabel('Correo electrónico').fill('usuario1@subastagt.test');
await page.getByLabel('Contraseña',{exact:true}).fill('Subasta2026!');
await page.getByRole('button',{name:'Iniciar sesión →'}).click();
await page.getByText('Hola, Usuario 1').waitFor();
await page.getByRole('button',{name:'Ver subasta'}).first().click();
await page.getByRole('heading',{name:'Ficha técnica'}).waitFor();
await page.screenshot({path:'test-results/detalle.png',fullPage:true});
await page.getByRole('button',{name:'Volver al inventario'}).click();
await page.getByPlaceholder('Marca, modelo o lote').fill('Corolla');
if(await page.locator('.vehicle-card').count()!==1)throw new Error('Filtro no funcionó');
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'test-results/movil.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Desbordamiento en móvil');
await browser.close();
if(errors.length)throw new Error(errors.join('\n'));
console.log('Navegador: inventario, login, detalle, filtros y móvil correctos.');
